### ISSUE TITLE
Bug Type Error: Cannot pass a defined object with defined nested type as `TLoggableEntry`

### ISSUE THREAD

**Issue by mikrowdev** [fp8/jlog-facade#15]
## Error
If you try to pass as `TLoggableEntry` an object that has a definition with nested defined object, in this case `IAddress` it gives a type error
```typescript
interface IAddress{
    line: string;
    city: string;
}

interface IUser{
    id: string;
    email: string;
    age: number;
    address: IAddress
}

const user: IUser = {
    id: 'jU1kyio90olkjhur4',
    email: 'user@test.com',
    age: 1,
    address: {
        city: 'Rome',
        line: 'line address'
    }
}

const logger = new JLogger('test_logger', LogLevel.INFO);
// this give an error for the payload described below
logger.info('message', {...user});
```
error recieved
```
Argument of type '{ id: string; email: string; age: number; address: IAddress; }' is not assignable to parameter of type 'TLoggableEntry'.
  Type '{ id: string; email: string; age: number; address: IAddress; }' is not assignable to type 'IJson'.
    Property 'address' is incompatible with index signature.
      Type 'IAddress' is not assignable to type 'TJsonValue | TJsonValue[]'.
        Type 'IAddress' is not assignable to type 'IJson'.
          Index signature for type 'string' is missing in type 'IAddress'.
```

**Comment by marcoslin** [comment]
Basically, the logger accept a [TLoggableParam](https://fp8.github.io/jlog-facade/types/TLoggableParam.html).  In other words, you have 2 options:

1. For a class, extend [AbstractLoggable](https://fp8.github.io/jlog-facade/classes/AbstractLoggable.html)
2. For interface, extend [IJson](https://fp8.github.io/jlog-facade/interfaces/IJson.html)

**Comment by mikrowdev** [comment]
@marcoslin yes i got the idea, but will be still useful to log objects that doesn't satisfy the `IJson` condition, for ie:

```typescript
logger.info('User logged in', Loggable.of('user',userInstance);
```
`Loggable.of` could be a method that try to parse the object into a valid IJson, allowing in this way the logs of javascript plain objects or any other possible object definition

**Comment by marcoslin** [comment]
Loggable created.  Please see warning in the doc: https://fp8.github.io/jlog-facade/classes/Loggable.html
