### ISSUE TITLE
Add support to have separate destinations for each `JLogger` instance 

### ISSUE THREAD

**Issue by mikrowdev** [fp8/jlog-facade#6]
It would be nice to have distinct destination for each `JLogger` instance, in this moment if you get two different instance of logger via factory they will share all the factory setted destinations as well
```typescript
// defining logger
const firstLogger: JLogger = LoggerFactory.create();
const secondLogger : JLogger = LoggerFactory.create();

// defining destinations, this will be shared with all the loggers
LoggerFactory.addLogDestination(destination)
```

**Comment by marcoslin** [comment]
This was implemented using filter in destination.  The filter can also be applied using logger.json: https://github.com/fp8/jlog-facade#configuration
